server:
  port: 8086
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/databasedacap"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  # Tự động tạo và cập nhật database schema (chọn 'none' nếu không muốn tự động tạo schema)
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.springframework: DEBUG
    com.example: DEBUG